### ISSUE TITLE
Add compact tag view

### ISSUE THREAD

**Issue by ianb** [ianb/pageshot#45]
It's hard to see more than one item at a time on the tag page.  Maybe some kind of list view would be appropriate.

**Comment by ianb** [comment]
I think this requires general UI consideration, I think it would be premature to add another view of tags just yet.  Something to keep in mind (for @brampitoyo?)

**Comment by brampitoyo** [comment]
Taking a step back, we’ll need a bit more investigation on the tag system. Tags may be necessary to organise many links, but why not use something that’s less versatile but more familiar like folders or coloured labels?
